CREATE DATABASE IF NOT EXISTS school1_db;
USE school1_db;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  passwordHash VARCHAR(255) NOT NULL,
  role ENUM('Teacher', 'Principal', 'President', 'Accountant') NOT NULL,
  name VARCHAR(255) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS students (
  reg VARCHAR(50) PRIMARY KEY,
  id VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  class VARCHAR(50) NOT NULL,
  section VARCHAR(50) NOT NULL,
  dob DATE NOT NULL,
  pname VARCHAR(255) NOT NULL,
  mob VARCHAR(30) NOT NULL,
  jDate DATE NOT NULL,
  lDate DATE NULL,
  addr TEXT NULL,
  guardianAddress TEXT NULL,
  aadhaarStudent VARCHAR(50) NULL,
  blood VARCHAR(20) NULL,
  motherAadhaar VARCHAR(50) NULL,
  fatherAadhaar VARCHAR(50) NULL,
  nationality VARCHAR(100) NULL,
  occupation VARCHAR(100) NULL,
  guardian VARCHAR(255) NULL,
  guardianOccupation VARCHAR(255) NULL,
  lastClass VARCHAR(50) NULL,
  prevSchool VARCHAR(255) NULL,
  tcDate DATE NULL,
  mark1 VARCHAR(255) NULL,
  mark2 VARCHAR(255) NULL,
  rem TEXT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS marks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  studentReg VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  exam VARCHAR(100) NOT NULL,
  marks JSON NOT NULL,
  total INT NOT NULL,
  maxTotal INT NOT NULL,
  percentage FLOAT NOT NULL,
  grade VARCHAR(10) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY student_exam_unique (studentReg, exam),
  CONSTRAINT fk_marks_student
    FOREIGN KEY (studentReg)
    REFERENCES students (reg)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS fees (
  id INT AUTO_INCREMENT PRIMARY KEY,
  studentReg VARCHAR(50) NOT NULL,
  total DECIMAL(12,2) NOT NULL,
  paid DECIMAL(12,2) NOT NULL,
  pending DECIMAL(12,2) NOT NULL,
  status VARCHAR(50) NOT NULL,
  mode VARCHAR(50) NOT NULL,
  date DATE NOT NULL,
  paymentTerm VARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_fees_student
    FOREIGN KEY (studentReg)
    REFERENCES students (reg)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
